// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl_hoGffULDYgs7JB4ZA4saeJJfFq8nwU',
    appId: '1:253983587346:web:d32d998035d1feb448accb',
    messagingSenderId: '253983587346',
    projectId: 'coupon-app-29446',
    authDomain: 'coupon-app-29446.firebaseapp.com',
    storageBucket: 'coupon-app-29446.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQXI3SFvC3gVOwEVMp3hXfbgxH_mjc3Tk',
    appId: '1:253983587346:android:f3d5e70ac2ff915c48accb',
    messagingSenderId: '253983587346',
    projectId: 'coupon-app-29446',
    storageBucket: 'coupon-app-29446.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpbE4CwcdXKcR6eP974IVB3m15yfIG3k8',
    appId: '1:253983587346:ios:2c7ff7d7b243e4e248accb',
    messagingSenderId: '253983587346',
    projectId: 'coupon-app-29446',
    storageBucket: 'coupon-app-29446.firebasestorage.app',
    androidClientId:
        '253983587346-9fh1d0d2m8upp17bv0rla8dj2410tk5a.apps.googleusercontent.com',
    iosClientId: '253983587346-2ofh0de9kqh45r57obv13gii570cih3r.apps.googleusercontent.com',
    iosBundleId: 'com.colesmartllc.bitesaver',
  );
}
